name: Build Kernel

on:
  push:
    branches:
      - main  # Измените на вашу основную ветку, если необходимо
  pull_request:
    branches:
      - main  # Измените на вашу основную ветку, если необходимо

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl unzip

      - name: Download Clang
        run: |
          wget https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20241222-release/Clang-20.0.0git-20241222.tar.gz
          tar -xzf Clang-20.0.0git-20241222.tar.gz
          # Проверяем, существует ли директория после извлечения
          if [ -d "Clang-20.0.0git-20241222" ]; then
            sudo mv Clang-20.0.0git-20241222 /usr/local/clang
          else
            echo "Ошибка: Директория Clang-20.0.0git-20241222 не найдена."
            exit 1
          fi

      - name: Set up Clang
        run: echo "/usr/local/clang/bin" >> $GITHUB_PATH

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 --branch kernel-tree https://github.com/Jbub5/android_kernel_xiaomi_mt6768.git kernel
          cd kernel
          git checkout lancelot_defconfig

      - name: Build Kernel
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make lancelot_defconfig
          make -j$(nproc)  # Используйте количество ядер вашего процессора

      - name: Clone AnyKernel3
        run: |
          git clone --depth=1 --branch proton https://github.com/Jbub5/AnyKernel3.git anykernel

      - name: Copy Kernel and Modules
        run: |
          cd kernel
          cp arch/arm64/boot/Image anykernel
          cp -r out/arch/arm64/boot/dts/* anykernel/dts/
          cp -r out/lib/modules/* anykernel/modules/

      - name: Package Kernel
        run: |
          cd anykernel
          zip -r ../kernel.zip *
